//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labyrinth.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album_Attachment
    {
        public int Id { get; set; }
        public int AlbumId { get; set; }
        public long AttachmentId { get; set; }
        public Nullable<int> CUser { get; set; }
        public System.DateTime CDate { get; set; }
    
        public virtual Attachment Attachment { get; set; }
    }
}
