//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Block
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public string PositionName { get; set; }
        public Nullable<int> NewsId { get; set; }
        public Nullable<int> SecID { get; set; }
        public Nullable<int> Type { get; set; }
        public string Link { get; set; }
    }
}
