//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conj_PluginPage_Plugin
    {
        public int Id { get; set; }
        public Nullable<int> PositionId { get; set; }
        public Nullable<int> PlugInId { get; set; }
        public Nullable<int> PageId { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    }
}
