//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labyrinth.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency_Daily
    {
        public int ID { get; set; }
        public int CurrencyID { get; set; }
        public int UnitID { get; set; }
        public double Purch_Price { get; set; }
        public double Sell_Price { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public int CUser { get; set; }
        public System.DateTime CDate { get; set; }
    }
}
