//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daily_Karats
    {
        public int ID { get; set; }
        public int GoldID { get; set; }
        public int KaratID { get; set; }
        public double Price_GoldMiths_EGP { get; set; }
        public double Price_ExChange_EGP { get; set; }
        public double Price_ExChange_USD { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public int CUser { get; set; }
        public System.DateTime CDate { get; set; }
    
        public virtual Karat Karat { get; set; }
        public virtual Gold Gold { get; set; }
    }
}
