//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralSettingsPage
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public bool Display { get; set; }
        public int PageID { get; set; }
    }
}
