//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gold
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gold()
        {
            this.Daily_Karats = new HashSet<Daily_Karats>();
            this.News_Golds = new HashSet<News_Golds>();
            this.NewsVersion_Golds = new HashSet<NewsVersion_Golds>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsActive { get; set; }
        public int CUser { get; set; }
        public System.DateTime CDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Daily_Karats> Daily_Karats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<News_Golds> News_Golds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewsVersion_Golds> NewsVersion_Golds { get; set; }
    }
}
