//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labyrinth.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupLink
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GroupLink()
        {
            this.Conj_News_Groups = new HashSet<Conj_News_Groups>();
            this.NewsOfSpecificGroups = new HashSet<NewsOfSpecificGroup>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CUser { get; set; }
        public System.DateTime CDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Conj_News_Groups> Conj_News_Groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewsOfSpecificGroup> NewsOfSpecificGroups { get; set; }
    }
}
