//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeadLine
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Link { get; set; }
        public bool IsActive { get; set; }
        public Nullable<long> AttachmentId { get; set; }
        public string AltImage { get; set; }
        public string Brief { get; set; }
        public string Subtitle1 { get; set; }
        public string Subtitle2 { get; set; }
        public string Subtitle3 { get; set; }
        public string Subtitle4 { get; set; }
        public string Subtitle5 { get; set; }
        public string Subtitle6 { get; set; }
        public int CUser { get; set; }
        public System.DateTime CDate { get; set; }
    
        public virtual Attachment Attachment { get; set; }
    }
}
