//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsSearch
    {
        public int NewsID { get; set; }
        public int DomainID { get; set; }
        public Nullable<int> SecID { get; set; }
        public Nullable<int> EditorID { get; set; }
        public Nullable<int> Type { get; set; }
        public string WrittenBy { get; set; }
        public string Title { get; set; }
        public string Brief { get; set; }
        public Nullable<System.DateTime> CDate { get; set; }
        public string ImageCaption { get; set; }
        public Nullable<int> AttachmentId { get; set; }
    }
}
