//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labyrinth.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public News()
        {
            this.News_Golds = new HashSet<News_Golds>();
            this.ViewsCounters = new HashSet<ViewsCounter>();
        }
    
        public int ID { get; set; }
        public int SecID { get; set; }
        public string WrittenBy { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string Brief { get; set; }
        public string Story { get; set; }
        public Nullable<long> AttachmentID { get; set; }
        public string ImageCaption { get; set; }
        public Nullable<long> Cover { get; set; }
        public string CoverCaption { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Status { get; set; }
        public bool IsApproved { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> CUser { get; set; }
        public System.DateTime CDate { get; set; }
        public string Embed { get; set; }
        public Nullable<int> CurrentGroup { get; set; }
        public Nullable<int> CurrentUser { get; set; }
        public Nullable<int> ViewsCount { get; set; }
        public string RelatedNews { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<News_Golds> News_Golds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ViewsCounter> ViewsCounters { get; set; }
    }
}
