//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labyrinth.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsVersion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NewsVersion()
        {
            this.NewsVersion_Albums = new HashSet<NewsVersion_Albums>();
            this.NewsVersion_Attachment = new HashSet<NewsVersion_Attachment>();
            this.NewsVersion_Golds = new HashSet<NewsVersion_Golds>();
            this.NewsVersionMates = new HashSet<NewsVersionMate>();
            this.NewsVersion_Poll = new HashSet<NewsVersion_Poll>();
            this.NewsVersion_Tags = new HashSet<NewsVersion_Tags>();
            this.NewsVersion_WorkFlowAttachment = new HashSet<NewsVersion_WorkFlowAttachment>();
        }
    
        public int Id { get; set; }
        public int NewsId { get; set; }
        public int SecId { get; set; }
        public string WrittenBy { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string Brief { get; set; }
        public string Story { get; set; }
        public Nullable<long> AttachmentId { get; set; }
        public string ImageCaption { get; set; }
        public Nullable<long> Cover { get; set; }
        public string CoverCaption { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> EditorId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CUser { get; set; }
        public System.DateTime CDate { get; set; }
        public System.DateTime UDate { get; set; }
        public string Embed { get; set; }
        public Nullable<int> CurrentGroup { get; set; }
        public Nullable<int> CurrentUser { get; set; }
        public string RelatedNews { get; set; }
        public Nullable<int> ViewsCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewsVersion_Albums> NewsVersion_Albums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewsVersion_Attachment> NewsVersion_Attachment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewsVersion_Golds> NewsVersion_Golds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewsVersionMate> NewsVersionMates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewsVersion_Poll> NewsVersion_Poll { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewsVersion_Tags> NewsVersion_Tags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewsVersion_WorkFlowAttachment> NewsVersion_WorkFlowAttachment { get; set; }
    }
}
