//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labyrinth.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class News_Albums
    {
        public int Id { get; set; }
        public int NewsId { get; set; }
        public int AlbumId { get; set; }
    
        public virtual Album Album { get; set; }
    }
}
