//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class News_Poll
    {
        public int Id { get; set; }
        public int PollId { get; set; }
        public int NewsID { get; set; }
    
        public virtual Poll Poll { get; set; }
    }
}
