//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class News_Reaction
    {
        public int NewsID { get; set; }
        public int Love { get; set; }
        public int Wow { get; set; }
        public int Sad { get; set; }
        public int Fun { get; set; }
        public int Great { get; set; }
    }
}
