//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsVersion_Attachment
    {
        public int Id { get; set; }
        public int NewsId { get; set; }
        public long AttachmentId { get; set; }
    
        public virtual Attachment Attachment { get; set; }
        public virtual NewsVersion NewsVersion { get; set; }
    }
}
