//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labyrinth.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPoll
    {
        public int Id { get; set; }
        public int SecID { get; set; }
        public int PollID { get; set; }
        public int DisplayOrder { get; set; }
    }
}
