//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labyrinth.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poll
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Poll()
        {
            this.News_Poll = new HashSet<News_Poll>();
            this.NewsVersion_Poll = new HashSet<NewsVersion_Poll>();
            this.PollAnswers = new HashSet<PollAnswer>();
        }
    
        public int Id { get; set; }
        public string Question { get; set; }
        public Nullable<int> SecId { get; set; }
        public Nullable<int> AttachmentId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> ToTalVotes { get; set; }
        public int Cuser { get; set; }
        public System.DateTime CDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<News_Poll> News_Poll { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewsVersion_Poll> NewsVersion_Poll { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PollAnswer> PollAnswers { get; set; }
    }
}
